# Form implementation generated from reading ui file 'folder_widget.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_folderWidget(object):
    def setupUi(self, folderWidget):
        folderWidget.setObjectName("folderWidget")
        folderWidget.resize(855, 26)
        self.verticalLayout = QtWidgets.QVBoxLayout(folderWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.folderHLayout = QtWidgets.QHBoxLayout()
        self.folderHLayout.setContentsMargins(-1, 0, -1, 0)
        self.folderHLayout.setObjectName("folderHLayout")
        self.folderLabel = QtWidgets.QLabel(parent=folderWidget)
        self.folderLabel.setObjectName("folderLabel")
        self.folderHLayout.addWidget(self.folderLabel)
        self.folderPathLabel = QtWidgets.QLabel(parent=folderWidget)
        palette = QtGui.QPalette()
        self.folderPathLabel.setPalette(palette)
        self.folderPathLabel.setObjectName("folderPathLabel")
        self.folderHLayout.addWidget(self.folderPathLabel)
        self.deleteButton = QtWidgets.QPushButton(parent=folderWidget)
        self.deleteButton.setMaximumSize(QtCore.QSize(25, 25))
        self.deleteButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/delete_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.deleteButton.setIcon(icon)
        self.deleteButton.setObjectName("deleteButton")
        self.folderHLayout.addWidget(self.deleteButton)
        self.verticalLayout.addLayout(self.folderHLayout)

        self.retranslateUi(folderWidget)
        QtCore.QMetaObject.connectSlotsByName(folderWidget)

    def retranslateUi(self, folderWidget):
        _translate = QtCore.QCoreApplication.translate
        folderWidget.setWindowTitle(_translate("folderWidget", "Folder"))
        self.folderLabel.setText(_translate("folderWidget", "Plex"))
        self.folderPathLabel.setText(_translate("folderWidget", "C:/Plex/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    folderWidget = QtWidgets.QWidget()
    ui = Ui_folderWidget()
    ui.setupUi(folderWidget)
    folderWidget.show()
    sys.exit(app.exec())
