# Form implementation generated from reading ui file 'no_items_widget.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_noItemsWidget(object):
    def setupUi(self, noItemsWidget):
        noItemsWidget.setObjectName("noItemsWidget")
        noItemsWidget.resize(750, 205)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(noItemsWidget.sizePolicy().hasHeightForWidth())
        noItemsWidget.setSizePolicy(sizePolicy)
        noItemsWidget.setMinimumSize(QtCore.QSize(0, 0))
        noItemsWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        noItemsWidget.setBaseSize(QtCore.QSize(0, 205))
        self.movieWidgetVLayout = QtWidgets.QVBoxLayout(noItemsWidget)
        self.movieWidgetVLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.movieWidgetVLayout.setContentsMargins(5, 5, 5, 5)
        self.movieWidgetVLayout.setSpacing(0)
        self.movieWidgetVLayout.setObjectName("movieWidgetVLayout")
        self.noItemRowWidget = QtWidgets.QWidget(parent=noItemsWidget)
        self.noItemRowWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.noItemRowWidget.setStyleSheet("#noItemRowWidget QLabel{color:white;}\n"
"\n"
"\n"
"\n"
"")
        self.noItemRowWidget.setObjectName("noItemRowWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.noItemRowWidget)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.itemArt = QtWidgets.QLabel(parent=self.noItemRowWidget)
        self.itemArt.setMinimumSize(QtCore.QSize(325, 150))
        self.itemArt.setMaximumSize(QtCore.QSize(100, 150))
        self.itemArt.setStyleSheet("")
        self.itemArt.setText("")
        self.itemArt.setPixmap(QtGui.QPixmap(":/images/delorean.png"))
        self.itemArt.setScaledContents(True)
        self.itemArt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.itemArt.setObjectName("itemArt")
        self.horizontalLayout.addWidget(self.itemArt)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.messageVLayout = QtWidgets.QVBoxLayout()
        self.messageVLayout.setObjectName("messageVLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.messageVLayout.addItem(spacerItem2)
        self.header = QtWidgets.QLabel(parent=self.noItemRowWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.header.setFont(font)
        self.header.setStyleSheet("QLabel { color: rgb(216, 138, 37); }")
        self.header.setObjectName("header")
        self.messageVLayout.addWidget(self.header)
        self.subHeader = QtWidgets.QLabel(parent=self.noItemRowWidget)
        self.subHeader.setMinimumSize(QtCore.QSize(400, 0))
        self.subHeader.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        self.subHeader.setFont(font)
        self.subHeader.setAutoFillBackground(False)
        self.subHeader.setWordWrap(True)
        self.subHeader.setObjectName("subHeader")
        self.messageVLayout.addWidget(self.subHeader)
        self.line = QtWidgets.QFrame(parent=self.noItemRowWidget)
        self.line.setStyleSheet("background-color: rgb(216, 138, 37);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.messageVLayout.addWidget(self.line)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.messageVLayout.addItem(spacerItem3)
        self.message = QtWidgets.QLabel(parent=self.noItemRowWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.message.setFont(font)
        self.message.setObjectName("message")
        self.messageVLayout.addWidget(self.message)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.messageVLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.messageVLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.movieWidgetVLayout.addWidget(self.noItemRowWidget)

        self.retranslateUi(noItemsWidget)
        QtCore.QMetaObject.connectSlotsByName(noItemsWidget)

    def retranslateUi(self, noItemsWidget):
        _translate = QtCore.QCoreApplication.translate
        noItemsWidget.setWindowTitle(_translate("noItemsWidget", "Movie"))
        self.header.setText(_translate("noItemsWidget", "Great Scott!"))
        self.subHeader.setText(_translate("noItemsWidget", "Looks like a problem with the Flux Capacitor.."))
        self.message.setText(_translate("noItemsWidget", "No items have been found.."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    noItemsWidget = QtWidgets.QWidget()
    ui = Ui_noItemsWidget()
    ui.setupUi(noItemsWidget)
    noItemsWidget.show()
    sys.exit(app.exec())
