# Form implementation generated from reading ui file 'scan.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Scan(object):
    def setupUi(self, Scan):
        Scan.setObjectName("Scan")
        Scan.resize(711, 339)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/scan_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Scan.setWindowIcon(icon)
        self.scanVLayout = QtWidgets.QVBoxLayout(Scan)
        self.scanVLayout.setContentsMargins(15, 15, 15, 15)
        self.scanVLayout.setSpacing(15)
        self.scanVLayout.setObjectName("scanVLayout")
        self.scanProgressTextLog = QtWidgets.QTextEdit(parent=Scan)
        self.scanProgressTextLog.setReadOnly(True)
        self.scanProgressTextLog.setObjectName("scanProgressTextLog")
        self.scanVLayout.addWidget(self.scanProgressTextLog)
        self.scanProgressBar = QtWidgets.QProgressBar(parent=Scan)
        self.scanProgressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.scanProgressBar.setFont(font)
        self.scanProgressBar.setProperty("value", 0)
        self.scanProgressBar.setObjectName("scanProgressBar")
        self.scanVLayout.addWidget(self.scanProgressBar)
        self.scanFooterHLayout = QtWidgets.QHBoxLayout()
        self.scanFooterHLayout.setContentsMargins(-1, -1, -1, 0)
        self.scanFooterHLayout.setObjectName("scanFooterHLayout")
        self.clearCacheCheckBox = QtWidgets.QCheckBox(parent=Scan)
        self.clearCacheCheckBox.setObjectName("clearCacheCheckBox")
        self.scanFooterHLayout.addWidget(self.clearCacheCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.scanFooterHLayout.addItem(spacerItem)
        self.scanButton = QtWidgets.QPushButton(parent=Scan)
        self.scanButton.setIcon(icon)
        self.scanButton.setObjectName("scanButton")
        self.scanFooterHLayout.addWidget(self.scanButton)
        self.scanVLayout.addLayout(self.scanFooterHLayout)

        self.retranslateUi(Scan)
        QtCore.QMetaObject.connectSlotsByName(Scan)

    def retranslateUi(self, Scan):
        _translate = QtCore.QCoreApplication.translate
        Scan.setWindowTitle(_translate("Scan", "Scanner"))
        self.scanProgressBar.setFormat(_translate("Scan", "%p%"))
        self.clearCacheCheckBox.setText(_translate("Scan", "Clear Cache"))
        self.scanButton.setText(_translate("Scan", "Scan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Scan = QtWidgets.QDialog()
    ui = Ui_Scan()
    ui.setupUi(Scan)
    Scan.show()
    sys.exit(app.exec())
